# Generated by Django 3.2.8 on 2021-10-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='videoId',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(max_length=500),
        ),
    ]
